[package]
name = "graphs-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
graphs = { path = "../graphs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
