version: '3.9'
services:
  llmhost:
    image: alpindale/aphrodite-openai:v0.6.1.post1
    volumes:
      - /home/tiny/mnt/drive/.cache/huggingface:/root/.cache/huggingface
    # restart: unless-stopped
    command: --model bjaidi/Phi-3-medium-128k-instruct-GPTQ-8-bit --served-model-name model --max-model-len 8192
    environment:
      CUDA_DEVICE_ORDER=PCI_BUS_ID
    ports:
      - "8000:2242"
    devices:
      - nvidia.com/gpu=all
