version: '3.9'
services:
  openaiapi:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    volumes:
      - /home/tiny/mnt/drive/gguf:/models
    ports:
      - "8003:8003"
    restart: unless-stopped
    command: -m /models/Phi-3-medium-4k-instruct-Q8_0.gguf --chat-template phi3 --port 8003 --host 0.0.0.0 -ngl 100 -fa --verbose --log-disable -c 8192
    devices:
      - nvidia.com/gpu=all

  chat-ui:
    image: localhost/chat-ui
    build: ./chat-ui
    ports:
      - "80:5173"
    restart: unless-stopped
    depends_on:
      - mongo-chatui
      - openaiapi

  mongo-chatui:
    image: mongo:latest
    restart: unless-stopped