version: '3.9'
services:
  openaiapi:
    image: localhost/agentflow
    build: ./agentflow
    ports:
      - "8003:8003"
    restart: unless-stopped
    env_file:
      - ./.agentflow.default.env
      - ./.agentflow.env
    depends_on:
      - llmhost
      - embedding-server
      - scraper

  llmhost:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    volumes:
      - /home/tiny/mnt/drive/gguf:/models
    restart: unless-stopped
    command: -m /models/Yi-1.5-9B-Chat-Q8_0.gguf --port 8003 --host 0.0.0.0 -ngl 100 -fa --verbose --log-disable -c 8192
    ports:
      - "8003:8003"
    devices:
      - nvidia.com/gpu=all

  chat-ui:
    image: localhost/chat-ui
    build: ./chat-ui
    ports:
      - "80:5173"
    restart: unless-stopped
    depends_on:
      - mongo-chatui
      - openaiapi

  embedding-server:
    image: localhost/embedding-server
    build: ./embedding-server
    ports:
      - "8001:8000"
    devices:
      - "nvidia.com/gpu=all"
    restart: unless-stopped

  scraper:
    image: localhost/scraper
    build: ./scraper
    ports:
      - "8002:8002"
    restart: unless-stopped

  mongo-chatui:
    image: mongo:latest
    restart: unless-stopped