version: '3.9'
services:
  openaiapi:
    image: localhost/agentflow
    build: ./agentflow
    ports:
      - "8003:8003"
    restart: unless-stopped
    env_file:
      - ./.agentflow.default.env
      - ./.agentflow.env
    depends_on:
      - llmhost
      - embedding-server
      - scraper
    environment:
      - EMBEDDING_URI=http://embedding-server:8000/embeddings
      - SCRAPER_URI=http://scraper:8002/scrape
      - OPENAI_URI=http://llmhost:8000
      - MODEL_NAME=modelname
    tty: true
    command: server http://llmhost:8000 http://embedding-server:8000/embeddings http://scraper:8002/scrape modelname -v --prompt-dir=Prompts 

  llmhost:
    # image: ghcr.io/ggerganov/llama.cpp:server-cuda
    image: localhost/llama.cpp
    volumes:
      - ${MODEL_DIR}:/models
    restart: unless-stopped
    command: -m /models/${MODEL_NAME} --metrics --port 8000 --host 0.0.0.0 -ngl 100 -fa --verbose --log-disable -c 8192
    ports:
      - "8000:8000"
    devices:
      - nvidia.com/gpu=all
    env_file:
      - ./.agentflow.default.env
      - ./.agentflow.env

  chat-ui:
    image: localhost/chat-ui
    build: ./chat-ui
    ports:
      - "80:5173"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo-chatui

  embedding-server:
    image: localhost/embedding-server
    build: ./embedding-server
    ports:
      - "8001:8000"
    devices:
      - "nvidia.com/gpu=all"
    restart: unless-stopped

  scraper:
    image: localhost/scraper
    build: ./scraper
    ports:
      - "8002:8002"
    restart: unless-stopped

  webprompt:
    image: localhost/webprompt
    build: ./webprompt
    ports:
      - "8004:3000"
    restart: unless-stopped

  mongo-chatui:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-storage:/data/db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  mongo-storage: