version: '3.8'
services:
  chat-ui:
    image: localhost/chat-ui
    ports:
      - "80:5173"
    restart: unless-stopped
    depends_on:
      - mongo-chatui
    networks:
      - internal_network
    environment:
      - "INFERENCE_SERVER_URI=http://${HOSTNAME}:8003/"

  embeddings-server:
    image: localhost/embeddingserver
    ports:
      - "8001:8000"
    devices:
      - "nvidia.com/gpu=all"
    restart: unless-stopped

  scraper:
    image: localhost/scraper
    ports:
      - "8002:8002"
    restart: unless-stopped
    networks:
      - internal_network

  mongo-chatui:
    image: mongo:latest
    restart: unless-stopped
    networks:
      - internal_network

networks:
  internal_network: