[package]
name = "graphs-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
graphs = { path = "../graphs" }
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"

[lints]
workspace = true
