@agentflow_server_HostAddress = http://localhost:8003

GET {{agentflow_server_HostAddress}}/transcripts/
Accept: application/json

###

POST {{agentflow_server_HostAddress}}/v1/chat/completions/
Accept: application/json
Content-Type: application/json

{
    "conversationId": "4567",
    "messages": [
        {
            "role": "user",
            "content": "hi"
        }
    ]
}

###
