[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
cellflow = { path = "../cellflow"}
agentflow = { path = "../agentflow"}
env_logger = "0.11"
log = "0.4"

[lints]
workspace = true
